import = ["~/.config/alacritty/rose-pine-moon.toml"]

[font]
size = 20

[font.normal]
family = "Hack Nerd Font"



[window]
decorations = "transparent"
opacity = 1.0
[window.padding]
x = 10
y = 10
[window.dimensions]
columns = 200
lines = 40
[window.position]
x = 0
y = 0

